### ISSUE TITLE
altv scripts?

### ISSUE THREAD

**Issue by Derodin** [pallhub/pallhub#1]
Hallo, 

Wollte mal fragen ob du Scripts anbeites? bzw. auch erstellen würdes. such jemand der mir js-sachen erstellt für altv

**Comment by pallhub** [comment]
Hey! 

Entschuldige für die Wartezeit, der Zeit biete ich keine Scripting Sachen an. Kannst dich gerne Per Discord melden, ich habe einige fertigen Scripte. Aktuell aus Privaten gründen erstelle ich keine Aufträge, Anfragen oder Support mit Längeren Wartezeiten. Melde dich einfach mal per Discord (PaLL#7182) mit dein Anliegen. Bedenke aber eine Längere wartezeit.

Grüße!
